http:
  port: 9080
admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: localhost
    paths: "/api"
  cats:
    methods: 'OPTIONS,GET,POST,PUT,PATCH,DELETE'
    cors: true 
    host: localhost
    paths: "/api/cats*"
  dogs:
    methods: 'OPTIONS,GET,POST,PUT,PATCH,DELETE'
    cors: true 
    host: localhost
    paths: "/api/dogs*"

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  catService:
    url: "http://localhost:9020"
  dogService:
    url: "http://localhost:9030"

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - jwt
  - verify-token

pipelines:
  default:
    apiEndpoints:
      - cats
      - dogs
    policies:
      - cors:
          - action:
              origin: 'http://localhost:3000'
              methods: 'OPTIONS,GET,POST,PUT,PATCH,DELETE'
              allowedHeaders: 'Authorization,Content-Type'
      - verify-token: {}
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: catService
              changeOrigin: true
      - proxy:
          - action:
              serviceEndpoint: dogService
              changeOrigin: true