version: '3.8'

services:
  webapi:
    build:
      context: ./appServer/DestinyLimoServer
      dockerfile: Dockerfile
    ports:
      - "5293:5293"
    network_mode: "host"
    volumes:
      - /home/chordify-services/lms-poc/prod/appServer/DestinyLimoServer/uploads/destiny-uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      restart_policy: 
        condition: any

  angular-app:
    build:
      context: ./ui
      dockerfile: Dockerfile
    deploy:
      restart_policy: 
        condition: any
    ports:
      - "9080:9080"

networks:
  default:
    name: my-lms-network