version: '3.8'

services:
  shared-micro-front-end-app:
    build:
      context: ./shared-micro-front-end-app
    container_name: shared-micro-front-end-app
    ports:
      - "8083:80" # Map port 8083 on the host to port 80 in the container
    networks:
      - mfe_network

  usermanagement:
    build:
      context: ./userManagement
    container_name: usermanagement
    ports:
      - "8087:80" # Map port 8087 on the host to port 80 in the container
    networks:
      - mfe_network

  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "8089:80" # Map port 8089 on the host to port 80 in the container
    networks:
      - mfe_network

  footer:
    build:
      context: ./footer
    container_name: footer
    ports:
      - "8081:80" # Map port 8081 on the host to port 80 in the container
    networks:
      - mfe_network

  header:
    build:
      context: ./header
    container_name: header
    ports:
      - "8082:80" # Map port 8082 on the host to port 80 in the container
    networks:
      - mfe_network

  host:
    build:
      context: ./host
    container_name: host
    ports:
      - []
    networks:
      - mfe_network

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: mfe-reverse-proxy
    ports:
      - "8086:80"     # Expose the reverse proxy on port 80
    depends_on:
      - shared-micro-front-end-app
      - usermanagement
      - dashboard
      - footer
      - header
      - host
    networks:
      - mfe_network
  
networks:
  mfe_network:
    driver: bridge
